### ISSUE TITLE
部分诗词出现乱码

### ISSUE THREAD

**Issue by kangzhun** [chinese-poetry/chinese-poetry-zhCN#2]
例如:poet.song.247000.json中
"author": "艾性夫",
    "paragraphs": [
      "锦袜生尘脱红玉，琼蟾夜抱金娥哭。",
      "芙蓉露瘦寒花钿，𫛛鹊楼空冷银烛。",
      "轻鸾小凤横紫箫，彩云密漾青霞绡。",
      "桂心沁入锁子骨，蕊宫贝阙天都遥。",
      "玉床梦断心欲死，独抱秋衾咽香髓。",
      "方瞳白羽青简书，驾月骑风渡瑶水。",
      "琼楼碧户翠雾香，紫兰结佩红薇囊。",
      "云车仙子不可识，芳卿寄谢真荒唐。",
      "蔗浆不饮啼寒泪，不悟齐人少翁诡。",
      "安得天上蓬莱宫，却着人间马嵬鬼。"
    ],
    "title": "临邛道士招魂歌"

**Comment by jackeyGao** [comment]
我在我的浏览器看到并没有乱码， 您的电脑可以没有安装适当的字体。
![image](https://user-images.githubusercontent.com/2869650/42144089-c76eca24-7deb-11e8-8da1-0cf3a5d56193.png)

可以在这里 [字体测试页](https://ctext.org/font-test-page/zh) 查看您电脑对古文字体的支持情况， 如果不能很好的显示， 链接的下方有安装字体包的方法。
