### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x96

### ISSUE THREAD

**Issue by fei4xu** [chinese-poetry/chinese-poetry-zhCN#3]
When I run `python trans.py` (windows 10, python 3.7.3), I got this error:

>D:\github\chinese-poetry-zhCN>python trans.py
Traceback (most recent call last):
  File "trans.py", line 31, in <module>
    list(map(trans, os.listdir(POETRY_DIRECTORY)))
  File "trans.py", line 16, in trans
    raw = open(file_path, 'r').read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x96 in position 27: illegal multibyte sequence

My windows 10 is in English.

**Comment by jackeyGao** [comment]
编码问题， 修复掉了。

**Comment by fei4xu** [comment]
another error:
>Traceback (most recent call last):
  File "trans.py", line 31, in <module>
    list(map(trans, os.listdir(POETRY_DIRECTORY)))
  File "trans.py", line 26, in trans
    f.write(content)
UnicodeEncodeError: 'gbk' codec can't encode character '\U00023e23' in position 11494: illegal multibyte sequence
